# NeoZork Pocket Hedge Fund - Production Configuration

# System Configuration
system:
  id: "neozork-pocket-hedge-fund"
  version: "1.0.0"
  environment: "production"
  debug_mode: false
  log_level: "INFO"
  max_workers: 8
  timeout_seconds: 30
  health_check_interval: 30
  metrics_interval: 60
  shutdown_timeout: 30

# Database Configuration
database:
  type: "postgresql"
  host: "postgres"
  port: 5432
  database: "neozork_hld_prediction"
  username: "neozork"
  password: "${POSTGRES_PASSWORD}"
  pool_size: 20
  max_overflow: 30
  pool_timeout: 30
  pool_recycle: 3600
  echo: false

# Redis Configuration
redis:
  host: "redis"
  port: 6379
  db: 0
  password: "${REDIS_PASSWORD}"
  max_connections: 50
  socket_timeout: 5
  socket_connect_timeout: 5
  retry_on_timeout: true

# JWT Configuration
jwt:
  secret_key: "${JWT_SECRET_KEY}"
  algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7
  issuer: "neozork-pocket-hedge-fund"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: false
  access_log: true
  cors_origins: ["https://neozork.com", "https://app.neozork.com"]
  rate_limit:
    requests_per_minute: 100
    burst_size: 200

# Security Configuration
security:
  ssl:
    enabled: true
    cert_path: "/etc/ssl/certs/neozork.crt"
    key_path: "/etc/ssl/private/neozork.key"
  firewall:
    enabled: true
    allowed_ports: [80, 443, 8000]
  secrets:
    encryption_key: "${ENCRYPTION_KEY}"
    salt_rounds: 12

# Monitoring Configuration
monitoring:
  prometheus:
    enabled: true
    port: 9090
    metrics_path: "/metrics"
  grafana:
    enabled: true
    port: 3000
    admin_password: "${GRAFANA_PASSWORD}"
  alerting:
    enabled: true
    webhook_url: "${ALERT_WEBHOOK_URL}"
    email:
      smtp_server: "${SMTP_SERVER}"
      smtp_port: 587
      username: "${SMTP_USERNAME}"
      password: "${SMTP_PASSWORD}"
      from_email: "alerts@neozork.com"

# Notification Configuration
notifications:
  email:
    provider: "smtp"
    smtp_server: "${SMTP_SERVER}"
    smtp_port: 587
    username: "${SMTP_USERNAME}"
    password: "${SMTP_PASSWORD}"
    from_email: "noreply@neozork.com"
    use_tls: true
  sms:
    provider: "twilio"
    account_sid: "${TWILIO_ACCOUNT_SID}"
    auth_token: "${TWILIO_AUTH_TOKEN}"
    from_number: "${TWILIO_FROM_NUMBER}"
  push:
    provider: "firebase"
    server_key: "${FIREBASE_SERVER_KEY}"
    project_id: "${FIREBASE_PROJECT_ID}"

# Strategy Engine Configuration
strategy_engine:
  max_concurrent_strategies: 10
  execution_interval: 60
  risk_limits:
    max_total_risk: 0.1
    max_position_size: 0.2
    max_drawdown: 0.15
  backtesting:
    max_data_points: 10000
    default_initial_capital: 100000

# Portfolio Configuration
portfolio:
  max_positions: 50
  rebalancing_threshold: 0.05
  transaction_fee: 0.001
  slippage_tolerance: 0.002

# Risk Management Configuration
risk_management:
  var_confidence_levels: [95, 99]
  max_leverage: 2.0
  stop_loss_threshold: 0.05
  take_profit_threshold: 0.10
  position_sizing:
    kelly_fraction: 0.25
    max_risk_per_trade: 0.02

# Performance Configuration
performance:
  cache_ttl: 300
  max_cache_size: 1000
  background_tasks:
    enabled: true
    max_workers: 4
    queue_size: 1000

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: "console"
      level: "INFO"
    - type: "file"
      level: "DEBUG"
      filename: "/var/log/neozork/app.log"
      max_bytes: 10485760
      backup_count: 5
    - type: "file"
      level: "ERROR"
      filename: "/var/log/neozork/error.log"
      max_bytes: 10485760
      backup_count: 5

# Backup Configuration
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention_days: 30
  storage:
    type: "s3"
    bucket: "${BACKUP_S3_BUCKET}"
    region: "${BACKUP_S3_REGION}"
    access_key: "${BACKUP_S3_ACCESS_KEY}"
    secret_key: "${BACKUP_S3_SECRET_KEY}"

# Scaling Configuration
scaling:
  auto_scaling:
    enabled: true
    min_replicas: 3
    max_replicas: 10
    target_cpu: 70
    target_memory: 80
    scale_up_cooldown: 300
    scale_down_cooldown: 600

# Feature Flags
features:
  strategy_marketplace: true
  investor_portal: true
  dashboard_analytics: true
  real_time_notifications: true
  advanced_risk_analytics: true
  backtesting_engine: true
  social_trading: false
  mobile_app: false
