services:
  neozork-hld:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_UV: ${USE_UV:-true}
        UV_ONLY: ${UV_ONLY:-true}
    volumes:
      # Mount local directories to the container
      - ./data:/app/data
      - ./logs:/app/logs
      - ./mql5_feed:/app/mql5_feed
      # Mount the results directory to access plots on the host
      - ./results:/app/results
      # Mount tests directory for pytest
      - ./tests:/app/tests
      # Mount UV cache for better performance
      - uv_cache:/app/.uv_cache
    env_file:
      - docker.env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DOCKER_CONTAINER=true
      - USE_UV=true
      - UV_ONLY=true
      - UV_CACHE_DIR=/app/.uv_cache
      - UV_VENV_DIR=/app/.venv
    # Interactive script execution with user prompts
    stdin_open: true
    tty: true
    # Use the entrypoint script instead of direct commands
    entrypoint: ["/app/docker-entrypoint.sh"]
    # Memory and resource limits - Increased for large dataset processing
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'
        reservations:
          memory: 4G
          cpus: '1.0'
    # Health check to monitor container status
    healthcheck:
      test: ["CMD", "python", "-c", "import psutil; print('Memory:', psutil.virtual_memory().percent, '%')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uv_cache:
    driver: local
