services:
  neozork-hld:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount local directories to the container
      - ./data:/app/data
      - ./logs:/app/logs
      - ./mql5_feed:/app/mql5_feed
    env_file:
      - .env
    # Interactive script execution with user prompts
    stdin_open: true
    tty: true
    # Use the entrypoint script instead of direct commands
    entrypoint: ["/app/docker-entrypoint.sh"]
