services:
  neozork-hld:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_UV: ${USE_UV:-true}
    volumes:
      # Mount local directories to the container
      - ./data:/app/data
      - ./logs:/app/logs
      - ./mql5_feed:/app/mql5_feed
      # Mount the results directory to access plots on the host
      - ./results:/app/results
      # Mount tests directory for pytest
      - ./tests:/app/tests
    env_file:
      - docker.env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DOCKER_CONTAINER=true
    # Interactive script execution with user prompts
    stdin_open: true
    tty: true
    # Use the entrypoint script instead of direct commands
    entrypoint: ["/app/docker-entrypoint.sh"]
