# uv.toml - configuration file for uv
# Documentation: https://docs.astral.sh/uv/configuration/

# Cache configuration
cache-dir = ".uv_cache"

# Index configuration
index-url = "https://pypi.org/simple"

# Python version preference
python-preference = "managed"

# Install packages without writing "*.pyc" files
compile-bytecode = false

# Resolution strategy
resolution = "highest"

# Prerelease handling - allow prereleases for compatibility
prerelease = "allow"
