# uv.toml - configuration file for uv
# Documentation: https://github.com/astral-sh/uv/blob/main/crates/uv-configuration/src/config.rs

[pip]
# Install packages without writing "*.pyc" files
compile-bytecode = false

# Dependency optimization
no-deps = false
only-binary = ["numpy", "pandas", "tensorflow", "torch", "scikit-learn", "scipy"]

# Index configuration
index-url = "https://pypi.org/simple"

[venv]
# By default, store virtual environments in this directory
venv-directory = ".venv"

[resolver]
# Enable a feature to allow overriding dependencies
allow-dependency-overrides = true
# Timeout for network operations (in seconds)
network-timeout = 30
