# uv.toml - configuration file for uv
# Documentation: https://github.com/astral-sh/uv/blob/main/crates/uv-configuration/src/config.rs

[pip]
# Install packages without writing "*.pyc" files
compile-bytecode = false

# Dependency optimization
no-deps = false
only-binary = ["numpy", "pandas", "tensorflow", "torch"]

[index]
# Use official PyPI
url = "https://pypi.org/simple"
