apiVersion: apps/v1
kind: Deployment
metadata:
  name: neozork-interactive-apple
  labels:
    app: neozork-interactive
    platform: apple-silicon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neozork-interactive
  template:
    metadata:
      labels:
        app: neozork-interactive
        platform: apple-silicon
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: neozork-interactive
        image: neozork-interactive:apple-latest
        ports:
        - containerPort: 8080
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: APPLE_SILICON
          value: "true"
        - name: MLX_ENABLED
          value: "true"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: logs-volume
          mountPath: /app/logs
        - name: plots-volume
          mountPath: /app/plots
        - name: results-volume
          mountPath: /app/results
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: neozork-data-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: neozork-logs-pvc
      - name: plots-volume
        persistentVolumeClaim:
          claimName: neozork-plots-pvc
      - name: results-volume
        persistentVolumeClaim:
          claimName: neozork-results-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: neozork-interactive-service
spec:
  selector:
    app: neozork-interactive
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neozork-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neozork-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neozork-plots-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neozork-results-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
