# AutoGluon Configuration
# This file contains the default configuration for AutoGluon integration

# AutoGluon presets for maximum quality
presets: "best_quality"

# Time limit for training (seconds)
time_limit: 3600

# Evaluation metric
eval_metric: "roc_auc"

# Validation settings
holdout_frac: 0.1
num_bag_folds: 0
num_bag_sets: 1

# Model selection (exclude GPU-dependent models for MacBook M1)
excluded_model_types: ["NN_TORCH", "NN_FASTAI"]

# Hyperparameter optimization (disabled for simplicity)
# hyperparameter_tune_kwargs:
#   num_trials: 10
#   search_strategy: "auto"

# Model ensemble settings
num_stack_levels: 0  # stacking levels
auto_stack: false
refit_full: true
save_space: false

# Performance settings
verbosity: 2

# GPU settings (disabled for MacBook M1)
use_gpu: false
num_gpus: 0

# Environment settings
os.environ["CUDA_VISIBLE_DEVICES"] = ""
